import Fastify from 'fastify';
import cors from '@fastify/cors';
import dotenv from 'dotenv';

dotenv.config();
const f = Fastify({ logger: true });
f.register(cors);

const css = 'body{font-family:system-ui,-apple-system,sans-serif;background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);min-height:100vh;display:flex;align-items:center;justify-content:center;margin:0;padding:20px}.container{background:white;border-radius:16px;padding:60px 40px;max-width:600px;box-shadow:0 20px 60px rgba(0,0,0,0.3);text-align:center}.logo{font-size:72px;font-weight:900;color:#667eea;margin-bottom:20px}h1{font-size:36px;color:#333;margin:0 0 16px}p{font-size:18px;color:#666;line-height:1.6;margin:0 0 40px}ul{list-style:none;text-align:left;margin:40px 0;padding:30px;background:#f8f9fa;border-radius:12px}li{padding:12px 0;color:#555}li:before{content:"✓ ";color:#667eea;font-weight:bold;margin-right:12px}.footer{margin-top:40px;padding-top:20px;border-top:1px solid #eee;font-size:14px;color:#999}a{color:#667eea;text-decoration:none;margin:0 12px}a:hover{text-decoration:underline}';

f.get('/', (r,p)=>p.type('text/html').send(`<html><head><style>${css}</style></head><body><div class="container"><div class="logo">S</div><h1>SCORA</h1><p>Your AI fitness coach that reads your body and adapts your training in real-time.</p><ul><li>Daily posture reads powered by AI</li><li>Real-time workout adaptation</li><li>Integrates Strava, Oura, Apple Health</li><li>Marketplace of human coaches</li></ul><div class="footer"><p>SCORA is in early access.</p><p><a href="/privacy">Privacy Policy</a> • <a href="/terms">Terms of Service</a></p></div></div></body></html>`));

f.get('/privacy', (r,p)=>p.type('text/html').send(`<html><head><style>body{font-family:system-ui,sans-serif;background:#f8f9fa;padding:40px 20px;line-height:1.8}div{max-width:800px;margin:0 auto;background:white;padding:40px;border-radius:8px;box-shadow:0 2px 8px rgba(0,0,0,0.1)}h1{font-size:32px;color:#333}h2{font-size:20px;color:#555;margin-top:30px}p{color:#666}</style></head><body><div><h1>Privacy Policy</h1><p style="color:#999;font-size:14px">Last updated: July 1, 2026</p><h2>1. Introduction</h2><p>SCORA operates the SCORA mobile application.</p><h2>2. Information Collection</h2><p>We collect fitness data from Strava, Oura, and Apple Health.</p><h2>3. Data Security</h2><p>We protect your personal data.</p><h2>4. Your Rights</h2><p>Contact hello@scora.app for access or deletion.</p></div></body></html>`));

f.get('/terms', (r,p)=>p.type('text/html').send(`<html><head><style>body{font-family:system-ui,sans-serif;background:#f8f9fa;padding:40px 20px;line-height:1.8}div{max-width:800px;margin:0 auto;background:white;padding:40px;border-radius:8px;box-shadow:0 2px 8px rgba(0,0,0,0.1)}h1{font-size:32px;color:#333}h2{font-size:20px;color:#555;margin-top:30px}p{color:#666}</style></head><body><div><h1>Terms of Service</h1><p style="color:#999;font-size:14px">Last updated: July 1, 2026</p><h2>1. Acceptance</h2><p>By using SCORA, you accept these terms.</p><h2>2. License</h2><p>Use SCORA for personal purposes only.</p><h2>3. Disclaimer</h2><p>SCORA is provided as-is.</p><h2>4. Limitation</h2><p>SCORA is not liable for damages.</p></div></body></html>`));

f.get('/health', (r,p)=>({ok:true}));

const SID='228067', SS=process.env.STRAVA_SECRET||'', SR='https://zonal-prosperity-production-3965.up.railway.app/api/auth/strava/callback';
f.get('/api/auth/strava', (r,p)=>p.redirect(302, `https://www.strava.com/oauth/authorize?client_id=${SID}&response_type=code&redirect_uri=${encodeURIComponent(SR)}&scope=read,activity:read_all`));
f.get('/api/auth/strava/callback', async(r,p)=>{const{code}=r.query;if(!code)return p.code(400).send({e:'no code'});try{const res=await fetch('https://www.strava.com/oauth/token',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({client_id:SID,client_secret:SS,code,grant_type:'authorization_code'})});if(!res.ok)return p.code(400).send({e:'failed'});const d=await res.json(),name=d.athlete.firstname,id=d.athlete.id,link=`scora://auth/success?athlete_id=${id}&name=${encodeURIComponent(name)}`;return(r.headers['user-agent']||'').includes('iPhone')?p.redirect(302,link):p.type('text/html').send(`<html><head><style>body{font-family:system-ui,sans-serif;display:flex;align-items:center;justify-content:center;height:100vh;margin:0;background:linear-gradient(135deg,#667eea,#764ba2)}.container{background:white;padding:40px;border-radius:12px;max-width:400px;text-align:center}h1{font-size:48px;margin:0}h2{margin:20px 0 10px;color:#333}p{margin:0 0 30px;color:#666}a{display:inline-block;padding:12px 24px;background:#667eea;color:white;text-decoration:none;border-radius:6px;font-weight:600}</style></head><body><div class="container"><h1>✅</h1><h2>Strava Connected</h2><p>Welcome, ${name}!</p><a href="${link}">Open SCORA</a></div></body></html>`);}catch(e){return p.code(500).send({e:'error'});}});

const OID=process.env.OURA_ID||'', OS=process.env.OURA_SECRET||'', OR='https://zonal-prosperity-production-3965.up.railway.app/api/auth/oura/callback';
f.get('/api/auth/oura', (r,p)=>p.redirect(302, `https://cloud.ouraring.com/oauth/authorize?client_id=${OID}&response_type=code&redirect_uri=${encodeURIComponent(OR)}&scope=personal`));
f.get('/api/auth/oura/callback', async(r,p)=>{const{code}=r.query;if(!code)return p.code(400).send({e:'no code'});try{const res=await fetch('https://api.ouraring.com/oauth/token',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({client_id:OID,client_secret:OS,code,grant_type:'authorization_code'})});if(!res.ok)return p.code(400).send({e:'failed'});const link='scora://auth/oura/success';return(r.headers['user-agent']||'').includes('iPhone')?p.redirect(302,link):p.type('text/html').send(`<html><head><style>body{font-family:system-ui,sans-serif;display:flex;align-items:center;justify-content:center;height:100vh;margin:0;background:linear-gradient(135deg,#667eea,#764ba2)}.container{background:white;padding:40px;border-radius:12px;max-width:400px;text-align:center}h1{font-size:48px;margin:0}h2{margin:20px 0 10px;color:#333}p{margin:0 0 30px;color:#666}a{display:inline-block;padding:12px 24px;background:#667eea;color:white;text-decoration:none;border-radius:6px;font-weight:600}</style></head><body><div class="container"><h1>✅</h1><h2>Oura Linked</h2><p>Your sleep data is connected!</p><a href="${link}">Open SCORA</a></div></body></html>`);}catch(e){return p.code(500).send({e:'error'});}});

f.listen({port:3000,host:'0.0.0.0'}, (e,a)=>{if(e){f.log.error(e);process.exit(1);}console.log(a);});
