import Fastify from 'fastify';
import cors from '@fastify/cors';
import dotenv from 'dotenv';

dotenv.config();
const f = Fastify({ logger: true });
f.register(cors);

f.get('/', (r,p)=>p.type('text/html').send(`<!DOCTYPE html><html><head><meta charset="UTF-8"><style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);min-height:100vh;display:flex;align-items:center;justify-content:center;padding:20px}.container{background:white;border-radius:20px;padding:60px 40px;max-width:640px;box-shadow:0 20px 80px rgba(0,0,0,0.3)}.logo{font-size:80px;font-weight:900;color:#667eea;margin-bottom:24px;text-align:center}h1{font-size:40px;color:#1a1a1a;margin-bottom:16px;text-align:center;font-weight:700}p{font-size:18px;color:#666;line-height:1.6;text-align:center;margin-bottom:40px}ul{list-style:none;margin:40px 0;padding:0}li{padding:16px 0;font-size:16px;color:#444;display:flex;align-items:center}li:before{content:"";display:inline-block;width:20px;height:20px;margin-right:12px;background:#667eea;border-radius:4px;flex-shrink:0}.footer{margin-top:50px;padding-top:20px;border-top:1px solid #e0e0e0;text-align:center;font-size:13px;color:#999}a{color:#667eea;text-decoration:none}a:hover{text-decoration:underline}</style></head><body><div class="container"><div class="logo">S</div><h1>SCORA</h1><p>AI fitness coach that reads your body and adapts your training.</p><ul><li>Daily posture reads</li><li>Real-time adaptation</li><li>Strava + Oura integration</li><li>Human coach marketplace</li></ul><div class="footer"><p>Early access</p><p><a href="/privacy">Privacy</a> | <a href="/terms">Terms</a></p></div></div></body></html>`));

f.get('/privacy', (r,p)=>p.type('text/html').send(`<!DOCTYPE html><html><head><meta charset="UTF-8"><style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;background:#f5f5f5;padding:40px 20px;line-height:1.7}div{max-width:800px;margin:0 auto;background:white;padding:50px 40px;border-radius:12px}h1{font-size:32px;color:#1a1a1a;margin-bottom:8px}p{color:#999;font-size:13px;margin-bottom:30px}h2{font-size:18px;color:#333;margin-top:30px;margin-bottom:12px}p{color:#666}</style></head><body><div><h1>Privacy Policy</h1><p>Updated July 1, 2026</p><h2>1. Data Collection</h2><p>We collect fitness data from Strava, Oura, and Apple Health with your permission.</p><h2>2. Security</h2><p>Your data is protected with industry-standard encryption.</p><h2>3. Your Rights</h2><p>Contact hello@scora.app to access or delete your data anytime.</p></div></body></html>`));

f.get('/terms', (r,p)=>p.type('text/html').send(`<!DOCTYPE html><html><head><meta charset="UTF-8"><style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;background:#f5f5f5;padding:40px 20px;line-height:1.7}div{max-width:800px;margin:0 auto;background:white;padding:50px 40px;border-radius:12px}h1{font-size:32px;color:#1a1a1a;margin-bottom:8px}p{color:#999;font-size:13px;margin-bottom:30px}h2{font-size:18px;color:#333;margin-top:30px;margin-bottom:12px}p{color:#666}</style></head><body><div><h1>Terms of Service</h1><p>Updated July 1, 2026</p><h2>1. Acceptance</h2><p>By using SCORA, you accept these terms.</p><h2>2. Usage</h2><p>Use SCORA only for personal, non-commercial purposes.</p><h2>3. Liability</h2><p>SCORA is provided as-is without warranties or liability for damages.</p></div></body></html>`));

f.get('/health', (r,p)=>({ok:true}));

const SID='228067',SS=process.env.STRAVA_SECRET||'',SR='https://zonal-prosperity-production-3965.up.railway.app/api/auth/strava/callback';
f.get('/api/auth/strava',(r,p)=>p.redirect(302,`https://www.strava.com/oauth/authorize?client_id=${SID}&response_type=code&redirect_uri=${encodeURIComponent(SR)}&scope=read,activity:read_all`));
f.get('/api/auth/strava/callback',async(r,p)=>{const{code}=r.query;if(!code)return p.code(400).send({e:'no code'});try{const res=await fetch('https://www.strava.com/oauth/token',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({client_id:SID,client_secret:SS,code,grant_type:'authorization_code'})});if(!res.ok)return p.code(400).send({e:'failed'});const d=await res.json(),name=d.athlete.firstname,id=d.athlete.id,link=`scora://auth/success?athlete_id=${id}&name=${encodeURIComponent(name)}`;return(r.headers['user-agent']||'').includes('iPhone')?p.redirect(302,link):p.type('text/html').send(`<html><head><style>body{font-family:system-ui,sans-serif;display:flex;align-items:center;justify-content:center;height:100vh;margin:0;background:linear-gradient(135deg,#667eea,#764ba2)}.c{background:white;padding:50px;border-radius:16px;max-width:400px;text-align:center;box-shadow:0 20px 60px rgba(0,0,0,0.3)}h1{font-size:56px;margin:0}h2{font-size:24px;color:#333;margin:20px 0 10px}p{color:#666;margin:0 0 30px}a{display:inline-block;padding:14px 32px;background:#667eea;color:white;text-decoration:none;border-radius:8px;font-weight:600}</style></head><body><div class="c"><h1>✓</h1><h2>Strava Linked</h2><p>${name}</p><a href="${link}">Open</a></div></body></html>`);}catch(e){return p.code(500).send({e:'error'});}});

const OID=process.env.OURA_ID||'',OS=process.env.OURA_SECRET||'',OR='https://zonal-prosperity-production-3965.up.railway.app/api/auth/oura/callback';
f.get('/api/auth/oura',(r,p)=>p.redirect(302,`https://cloud.ouraring.com/oauth/authorize?client_id=${OID}&response_type=code&redirect_uri=${encodeURIComponent(OR)}&scope=personal`));
f.get('/api/auth/oura/callback',async(r,p)=>{const{code}=r.query;if(!code)return p.code(400).send({e:'no code'});try{const res=await fetch('https://api.ouraring.com/oauth/token',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({client_id:OID,client_secret:OS,code,grant_type:'authorization_code'})});if(!res.ok)return p.code(400).send({e:'failed'});const link='scora://auth/oura/success';return(r.headers['user-agent']||'').includes('iPhone')?p.redirect(302,link):p.type('text/html').send(`<html><head><style>body{font-family:system-ui,sans-serif;display:flex;align-items:center;justify-content:center;height:100vh;margin:0;background:linear-gradient(135deg,#667eea,#764ba2)}.c{background:white;padding:50px;border-radius:16px;max-width:400px;text-align:center;box-shadow:0 20px 60px rgba(0,0,0,0.3)}h1{font-size:56px;margin:0}h2{font-size:24px;color:#333;margin:20px 0 10px}p{color:#666;margin:0 0 30px}a{display:inline-block;padding:14px 32px;background:#667eea;color:white;text-decoration:none;border-radius:8px;font-weight:600}</style></head><body><div class="c"><h1>✓</h1><h2>Oura Linked</h2><p>Connected</p><a href="${link}">Open</a></div></body></html>`);}catch(e){return p.code(500).send({e:'error'});}});

f.listen({port:3000,host:'0.0.0.0'},(e,a)=>{if(e){f.log.error(e);process.exit(1);}console.log(a);});
